[workspace]
resolver = "2"
members = [
    "node",
    "crates/auto-config",
    "crates/core-primitives",
    "crates/das-primitives",
    "crates/frame-executive-ext",
    "crates/frame-system-ext",
    "crates/melo-erasure-coding",
    "crates/network-das",
    "crates/pallet-melo-store",
    "runtime",
]

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"
lto = "fat"
codegen-units = 1