[workspace]
members = [
    "node",
    "primitives",
    "crates/*",
    "pallets/template",
    "runtime",
]

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"
lto = "fat"
codegen-units = 1
